### ISSUE TITLE
What do you use this for?

### ISSUE THREAD

**Issue by JesseTG** [ilmola/generator#13]
Out of curiosity.

**Comment by ilmola** [comment]
Many years ago when C++11 was still called C++0x it was part a simple pinball game to make the ball, bumpers etc.
The game never went anywhere, but the code was lying on the hard-drive so I separated the generator part to a library, cleaned it a bit and uploaded github.

**Comment by JesseTG** [comment]
Ah, cool.  Good move; this sort of library looks like it'd be very useful for graphics tools or render tests or similar (that's what I'm using it for, actually).  It's definitely adding value to my own project.
