### ISSUE TITLE
How set are you on using your own math library?

### ISSUE THREAD

**Issue by JesseTG** [ilmola/generator#4]
I think GLM would be a better fit, personally, as it's similarly lightweight and more maintained.  But if you'd like, I can compromise and let the user pick between GLM and GML at compile-time.

**Comment by ilmola** [comment]
I did consider GLM, but did not want to add an external dependency and thought my library was much simpler.
Of course anyone else using GLM my math library is an external dependency.
Having the ability to choose a math library at compile time would be great if it can be made to work.

**Comment by JesseTG** [comment]
It's mostly done, actually #5 , but the rounded box looks weird for some reason and I want to figure out why.  It's a lucky coincidence because both GML and GLM follow a lot of GLSL's conventions, so all I have to do is write some `using` declarations and substitute some functionality that doesn't use the same name.

I think the main issue, however, is maintainability.  New functionality will have to be tested and maintained with two libraries.

Let's move discussion to #5
