### ISSUE TITLE
When using GLM, rounded box mesh corners are pointy

### ISSUE THREAD

**Issue by JesseTG** [ilmola/generator#6]
This should not be the case.

**Comment by ilmola** [comment]
There seems to be difference between gml and glm slerp implementation.
Try:

```
const auto a = gml::slerp(gml::vec3{0.176777f, 0.0f, 0.176777f}, gml::vec3{0.0f, 0.176777f, 0.176777f}, 0.5f);  
const auto b = glm::slerp(glm::vec3{0.176777f, 0.0f, 0.176777f}, glm::vec3{0.0f, 0.176777f, 0.176777f}, 0.5f);

std::cerr << "GML: " << a << "\n";
std::cerr << "GLM: (" << b[0] << "," << b[1] << "," << b[2] << ")\n";

std::cerr << "Expected length: " << length(gml::vec3{0.176777f, 0.0f, 0.176777f}) << "\n";
std::cerr << "GML: " << length(a) << ", GLM: " << length(b) << "\n";
```

Prints:
GML: (0.102062,0.102062,0.204124)
GLM: (0.123092,0.123092,0.246183)
Expected length: 0.25
GML: 0.25, GLM: 0.301512

**Comment by JesseTG** [comment]
Ah, that must be it.  I'll send a PR later today, thanks!

**Comment by JesseTG** [comment]
Hm, that may not be it.  Is it possible that one of the constructors may have different semantics?

**Comment by JesseTG** [comment]
Wait, no, I think your implementation of `angle` is different.  You normalize the vectors, but `glm` doesn't.

**EDIT:** Yep, that was it!  PR incoming.
